# Módulos de `Python`: `numpy`

## `numpy`

[numpy](https://numpy.org/) es es una librería que permite una manipulación **eficiente** de **arrays multidimensionales**, proporcionando una serie de métodos de conveniencia para su uso en **contextos científicos**.

El objeto array de `numpy` recibe el nombre de `ndarray`. Este tipo de dato es muy usado en el mundo de la ciencia de datos, donde la velocidad y los recursos son de gran importancia.

In [2]:
import numpy as np

#### Creando arrays

Para crear un `ndarray` usamos el método `.array()`.

Lo podemos hacer a partir de una lista:

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


O bien, a partir de una tupla:

In [6]:
b = np.array((1, 2, 3, 4, 5, 6, 7))
print(b)

[1 2 3 4 5 6 7]


In [7]:
print(type(b))

<class 'numpy.ndarray'>


Podemos crear secuencias de números mediante el método `arange`:

Aparte de *np.array* tenemos:

- *np.zeros(s)*: crea un array con 0s (float) con el *shape* indicado<br>

- *np.zeros_like(a)*: crea un array con 0s (float) con el mismo *shape* que el del array *a*<br>

- *np.ones(s)*: crea un array con 1s (float) con el *shape* indicado<br>

- *np.ones_like(a)*: crea un array con 1s (float) con el mismo *shape* que el del array *a*<br>

- *np.empty(s)*: crea un array con el *shape* indicado sin inicializar<br>

- *np.empty_like(a)*: crea un array con el *shape* de *a* sin inicializar<br>

- *np.arange(n)*: la versión np de *range*

- *np.eye(n)*, *np.identity(n)*: matriz diagonal de nxn

In [16]:
np_arr = np.arange(10)
print(np_arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
np_arr = np.arange(10, 1000, 10)
print(np_arr)


[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]


La diferencia es que `numpy` es **mucho** más rápido. Por ejemplo, vamos a medir cuánto se tardaría en multiplicar los elementos de la lista nativa de `Python` y de `numpy` por 2:

In [9]:
%%time
py_arr = list(range(10, 10000, 10))
[x * 2 for x in py_arr]

CPU times: user 197 μs, sys: 0 ns, total: 197 μs
Wall time: 204 μs


[20,
 40,
 60,
 80,
 100,
 120,
 140,
 160,
 180,
 200,
 220,
 240,
 260,
 280,
 300,
 320,
 340,
 360,
 380,
 400,
 420,
 440,
 460,
 480,
 500,
 520,
 540,
 560,
 580,
 600,
 620,
 640,
 660,
 680,
 700,
 720,
 740,
 760,
 780,
 800,
 820,
 840,
 860,
 880,
 900,
 920,
 940,
 960,
 980,
 1000,
 1020,
 1040,
 1060,
 1080,
 1100,
 1120,
 1140,
 1160,
 1180,
 1200,
 1220,
 1240,
 1260,
 1280,
 1300,
 1320,
 1340,
 1360,
 1380,
 1400,
 1420,
 1440,
 1460,
 1480,
 1500,
 1520,
 1540,
 1560,
 1580,
 1600,
 1620,
 1640,
 1660,
 1680,
 1700,
 1720,
 1740,
 1760,
 1780,
 1800,
 1820,
 1840,
 1860,
 1880,
 1900,
 1920,
 1940,
 1960,
 1980,
 2000,
 2020,
 2040,
 2060,
 2080,
 2100,
 2120,
 2140,
 2160,
 2180,
 2200,
 2220,
 2240,
 2260,
 2280,
 2300,
 2320,
 2340,
 2360,
 2380,
 2400,
 2420,
 2440,
 2460,
 2480,
 2500,
 2520,
 2540,
 2560,
 2580,
 2600,
 2620,
 2640,
 2660,
 2680,
 2700,
 2720,
 2740,
 2760,
 2780,
 2800,
 2820,
 2840,
 2860,
 2880,
 2900,
 2920,
 2940,
 2960,
 2980,
 3000,
 30

In [10]:
%%time
np_arr = np.arange(10, 10000, 10)
np_arr*2

CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 4.95 ms


array([   20,    40,    60,    80,   100,   120,   140,   160,   180,
         200,   220,   240,   260,   280,   300,   320,   340,   360,
         380,   400,   420,   440,   460,   480,   500,   520,   540,
         560,   580,   600,   620,   640,   660,   680,   700,   720,
         740,   760,   780,   800,   820,   840,   860,   880,   900,
         920,   940,   960,   980,  1000,  1020,  1040,  1060,  1080,
        1100,  1120,  1140,  1160,  1180,  1200,  1220,  1240,  1260,
        1280,  1300,  1320,  1340,  1360,  1380,  1400,  1420,  1440,
        1460,  1480,  1500,  1520,  1540,  1560,  1580,  1600,  1620,
        1640,  1660,  1680,  1700,  1720,  1740,  1760,  1780,  1800,
        1820,  1840,  1860,  1880,  1900,  1920,  1940,  1960,  1980,
        2000,  2020,  2040,  2060,  2080,  2100,  2120,  2140,  2160,
        2180,  2200,  2220,  2240,  2260,  2280,  2300,  2320,  2340,
        2360,  2380,  2400,  2420,  2440,  2460,  2480,  2500,  2520,
        2540,  2560,

### Dimensiones de un array

La dimensión de una array viene dada por el nivel de profundidad de éste.

Para saber la dimensión de un array, podemos usar la propiedad `.ndim`

**¡Cuidado!**. Si creamos un array $n$-dimensional, entonces todos los arrays de dimensión fija $m < n$, deben contener el mismo número de elementos. Es decir, si creamos un array de 4 dimensiones, todos los arrays de 3 dimensiones deben tener el mismo número de elementos; por su parte, todos los arrays de 2 dimensiones, deben tener el mismo número de elementos; y lo mismo para los arrays 1-dimensionales. Esto se debe a que en caso contrario, el atributo `.shape` que veremos a continuación no tendría sentido.

#### Arrays 0-dimensionales

Son los arrays constantes:

In [10]:
d0 = np.array(77)
d0.ndim

0

#### Arrays 1-dimensionales

Son los arrays con un solo nivel de profundidad

In [11]:
d1 = np.array([-1, 0, 1])
d1.ndim

1

#### Arrays 2-dimensionales

Son los arrays que tienen por elementos arrays unidimensionales:

In [12]:
d2 = np.array([[-3, -2], [-1, 0]])
d2.ndim

2

#### Arrays 3-dimensionales

Son los arrays que tinenen por elementos arrays bidimensionales:

In [13]:
d3 = np.array([[[1, 2, 3, 4], [4, 3, 2, 1]], [[1, 0, 1, 0], [-1, 1, -1, 1]]])
d3.ndim

3

### `Shape` de un array

**Shape.** Es el número de elementos de cada dimensión.

Lo calculamos con el atributo `.shape`

In [11]:
# Hay 3 elementos en el array 1-dimensional
d1 = np.array([-1, 0, 1])
d1.shape

(3,)

In [12]:
# Hay 2 elementos en el array 2D y 2 elementos en los arrays 1D
d2 = np.array([[-3, -2], [-1, 0]])
d2.shape

(2, 2)

In [13]:
# Hay 2 elementos en el array 3D, 2 elementos en cada array 2D y 4 elementos en cada array 1D
d3 = np.array([[[1, 2, 3, 4], [4, 3, 2, 1]], [[1, 0, 1, 0], [-1, 1, -1, 1]]])
d3.shape

(2, 2, 4)

La tupla resultante del atributo `.shape` se interpreta del siguiente modo: 
* Cada elemento de la tupla nos indica el número de elementos que hay en cada dimensión.
* El primer índice se corresponde con la mayor dimensión, correspondiente al valor obtenido con `ndim`. 
* El último índice se corresponde con la menor dimensión (dimensión 1).

Aquí es donde podemo observar la razón por la cuál todos los arrays de misma dimensión $m$ pertenecientes a un array $n$-dimensional, debe tener el mismo número de elementos.

### Elementos de un array


Podemos acceder a los elementos de un array con la sintaxis `[]`.

In [15]:
a = np.array([2, 3, 4, 5, 6])
print(a)

print("Primer elemento = ", a[0])
print("Segundo elemento = ", a[1])
print("Último elemento = ", a[-1])

[2 3 4 5 6]
Primer elemento =  2
Segundo elemento =  3
Último elemento =  6


In [18]:
a = np.array([[[1, 2, 3], [-3, -2, -1]], [[4, 5, 6], [7, 8, 9]]])
a.ndim

3

In [19]:
a[1, 1, 0]

7

Al igual que para el caso de las listas, los elementos de los `ndarrays` también pueden ser accedidos mediante índices negativos. 

El índice `-1` hace referencia al último elemento; el `-2`, al penúltimo; el `-3` al antepenúltimo; y así sucesivamente.

### Slicing

En `Python`, **slicing** hace referencia a tomar elementos desde un índice dado hasta otro proporcionado.

Ya conocemos la sintaxis:

* `[inicio:fin]` donde iremos desde el índice `inicio` hasta el índice `fin`-1, y lo haremos de 1 en 1
* `[inicio:fin:paso]` donde iremos desde el índice `inicio` hasta el índice `fin`-1, y lo haremos de `paso` en `paso`



In [20]:
# Array unidimensional
a1 = np.array([9, 8, 7, 6, 5, 4, 3])
a1

array([9, 8, 7, 6, 5, 4, 3])

In [21]:
# Del segundo elemento al cuarto de 1 en 1
a1[1:4]

array([8, 7, 6])

In [22]:
# Del primer elemento al sexto de 1 en 1
a1[:6]

array([9, 8, 7, 6, 5, 4])

In [23]:
# Del tercer elemento al último de 1 en 1
a1[2:]

array([7, 6, 5, 4, 3])

In [24]:
# Del segundo elemento al sexto de 2 en 2
a1[1:6:2]

array([8, 6, 4])

In [25]:
# Del primer elemento al quinto de 2 en 2
a1[:5:2]

array([9, 7, 5])

In [26]:
# Del segundo elemento al último de 3 en 3
a1[2::3]

array([7, 4])

In [27]:
# Del primer elemento al último de 4 en 4
a1[::4]

array([9, 5])

### Filtrando arrays

Filtrar un array implica la selección de elementos de un array existente que satisfagan una condición y crear un nuevo array con dichos elementos.

La sintaxis es muy similar al slicing, pero en vez de eso, entre corchetes indicamos una condición booleana. Los elementos que satisfagan la condición serán los que permanezcan, mientras que el resto serán omitidos.

Visto de otro modo, la condición crea un array booleano. Aquellas posiciones ocupadas por un `True` serán las contenidas en el array filtrado, mientras que las que estén ocupadas por `False` (porque no satisfacen la condición), serán descartadas.

In [28]:
a = np.array([4, 3, 2, 3, 4])
b = a[a == 4]
print(b)

[4 4]


In [29]:
a == 4

array([ True, False, False, False,  True])

In [30]:
c = a[a % 2 == 0]
print(c)

[4 2 4]


In [31]:
d = a[a <= 2]
print(d)

[2]


### Copias de arrays

**Copia.** Una copia de un array crea un nuevo array exactamente igual al original.

La copia no es afectada por los cambios aplicados en el array original.

In [32]:
x = np.array(["a", "b", "c"])
print(x)
x_copy = x.copy()
print(x_copy)

['a' 'b' 'c']
['a' 'b' 'c']


Como vemos, cada vez que aumentamos la dimensión del array, hay que anidar bucles `for` para imprimir cada uno de los elementos de los arrays 1D.

#### El método `.nditer()`

El método `.nditer()`, que nos crea un iterable el cual nos permite imprimir todos los elementos de los arrays:

In [33]:
for i in np.nditer(d3):
  print(i)

1
2
3
4
4
3
2
1
1
0
1
0
-1
1
-1
1


El método `.nditer()` también nos permite iterar con distinto paso (de 1 en 1, de 2 en 2, ...)

In [3]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])
for i in np.nditer(d2[:, ::2]):
  print(i)

1
3
5


#### El método `.ndenumerate()`

A veces necesitamos el índice correspondiente al elemento durante la iteración. El método `.ndenumerate()` nos proporciona dicha información.



In [35]:
d1 = np.array(["a", "b", "c"])

for idx, i in np.ndenumerate(d1):
  print("Índice:", idx,"Elemento:", i)

Índice: (0,) Elemento: a
Índice: (1,) Elemento: b
Índice: (2,) Elemento: c


In [36]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])

for idx, i in np.ndenumerate(d2):
  print("Índice:", idx,"Elemento:", i)

Índice: (0, 0) Elemento: 1
Índice: (0, 1) Elemento: 2
Índice: (1, 0) Elemento: 3
Índice: (1, 1) Elemento: 4
Índice: (2, 0) Elemento: 5
Índice: (2, 1) Elemento: 6


In [37]:
d3 = np.array([[["a", "b", "c", "d"], ["e", "f", "g", "h"]], [[1, 2, 3, 4], [5, 6, 7, 8]]])

for idx, i in np.ndenumerate(d3):
  print("Índice:", idx,"Elemento:", i)

Índice: (0, 0, 0) Elemento: a
Índice: (0, 0, 1) Elemento: b
Índice: (0, 0, 2) Elemento: c
Índice: (0, 0, 3) Elemento: d
Índice: (0, 1, 0) Elemento: e
Índice: (0, 1, 1) Elemento: f
Índice: (0, 1, 2) Elemento: g
Índice: (0, 1, 3) Elemento: h
Índice: (1, 0, 0) Elemento: 1
Índice: (1, 0, 1) Elemento: 2
Índice: (1, 0, 2) Elemento: 3
Índice: (1, 0, 3) Elemento: 4
Índice: (1, 1, 0) Elemento: 5
Índice: (1, 1, 1) Elemento: 6
Índice: (1, 1, 2) Elemento: 7
Índice: (1, 1, 3) Elemento: 8


### Concatenación de arrays

Para concatenar arrays, es decir, juntar dos o más arrays en un único array, usamos el método `.concatenate()`

In [38]:
# Conatenamos arrays 1D
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
a = np.concatenate((a1, a2))
print(a)

[-3 -2 -1  1  2  3]


In [39]:
# Concatenamos arrays 2D
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])

# Con axis = 0
b = np.concatenate((b1, b2), axis = 0)
print("axis = 0 nos devuelve\n", b)

# Con axis = 1
b = np.concatenate((b1, b2), axis = 1)
print("\naxis = 1 nos devuelve\n", b)

axis = 0 nos devuelve
 [[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 1  2]
 [ 3  4]
 [ 5  6]]

axis = 1 nos devuelve
 [[-6 -5  1  2]
 [-4 -3  3  4]
 [-2 -1  5  6]]


### Division de arrays

Para dividir arrays en varios arrays por filas o columnas usamos el etodo '.split()'

In [70]:
import numpy as np
a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
n=3
b, c, d = np.split(a, n,  axis=0) #a = array, n = dividir array en n arrays iguales, axis = modo de division (0= Vertical, 1= Horizontal)
print(b)
print("--------------\n")
print(c)
print("--------------\n")
print(d)

[[ 1  2  3]
 [-1  0  1]]
--------------

[[ 4  5  6]
 [-4  0  4]]
--------------

[[ 3  2  1]
 [-3  0  3]]


In [71]:
import numpy as np
a = np.array([[1, 2, 3], [-1, 0, 1],[4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
n=3
b, c, d = np.hsplit(a, n) #a = array, n = dividir array en n arrays iguales, axis = modo de division (0= Vertical, 1= Horizontal)
print(b)
print("--------------\n")
print(c)
print("--------------\n")
print(d)

[[ 1]
 [-1]
 [ 4]
 [-4]
 [ 3]
 [-3]]
--------------

[[2]
 [0]
 [5]
 [0]
 [2]
 [0]]
--------------

[[3]
 [1]
 [6]
 [4]
 [1]
 [3]]


### Buscando elementos en un array

Podemos buscar elementos en concreto de un array con el método `.where()` que nos devolverá un array de índices en los cuales se encuentra el elemento que estamos buscando.

Por ejemplo, dado el siguiente array 1D `x`, busquemos en qué posiciones éste toma el valor 0. 

In [40]:
x = np.array([1, 0, -1, 0, 2, 0, -2, 0])
idx0 = np.where(x == 0) 

print(idx0)

(array([1, 3, 5, 7]),)


Como resultado hemos obtenido que en los índices 1, 3, 5 y 7 del array `x` se toma el valor 0.

In [41]:
y = np.array([[2, 3, 6, 7],
              [14, 15, 30, 31]])
z = np.where(y % 2 == 0)

print(z)

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))


### Ordenando arrays

Ordenar arrays implica reordenar los elementos siguiendo una secuencia ordenada.

A su vez, una secuencia ordenada es cualquier sucesión que tiene un orden cuyos elementos siguen, como por ejemplo el orden alfabético o numérico, tanto ascendente como descendente.

Para ordenar los elementos de un array, disponemos del método `.sort()`

In [42]:
x = np.array(["caracol", "mariposa", "escarabajo", "perezoso", "armadillo"])
print(np.sort(x))

['armadillo' 'caracol' 'escarabajo' 'mariposa' 'perezoso']


In [43]:
x = np.array([2.5, -2.3, 5.1, -5.7, 10.9, -10.6, 0.4])
print(np.sort(x))

[-10.6  -5.7  -2.3   0.4   2.5   5.1  10.9]


In [44]:
y = np.array([[2, 4, 3], [-4, -2, -3]])
print(np.sort(y))

[[ 2  3  4]
 [-4 -3 -2]]


### Elementos aleatorios en `numpy`

**Número aleatorio.** Un número aleatorio singifica que se trata de un número que no puede ser predicho lógicamente.




#### El módulo `random`

`numpy` tiene el módulo `random` dedicado a trabajar con números aleatorios

Para generar números enteros aleatorios, usamos el método `.randint()`


In [41]:
from numpy import random

In [42]:
# Generamos un número entero aleatorio del 1 al 20
n = random.randint(1, 20)
print(n)

1


In [43]:
# Generamos un número entero aleatorio del 0 al 10
m = random.randint(10)
print(m)

9


Para generar números reales aleatorios dentro del intervalo $[0, 1]$, usamos el método `.rand()`

In [44]:
# Generamos un número real aleatorio entre el 0 y el 1
x = random.rand()
print(x)

0.7934032714244456


#### Arrays aleatorios

Podemos generar arrays aleatorios tanto con el método `.randint()` como con el método `.rand()`

In [45]:
# Generamos un array 1D de 5 elementos enteros aleatorios
a = random.randint(100, size = 5)
print(a)

[80 32 26 18  8]


In [46]:
# Generamos un array 2D de 5 arrays 1D cada uno con 4 enteros aleatorios
c = random.randint(50, size = (5, 4))
print(c)

[[21 42 49 38]
 [29 49 30  4]
 [10 45  7 41]
 [ 4 39 41  0]
 [20 40 45 14]]


In [47]:
# Generamos un array 3D de 2 arrays 2D cada uno con 4 arrays 1D
#   cada uno con 3 reales aleatorios que esteñn en el intervalo [0,1]
d = random.rand(2, 4, 3)
print(d)

[[[9.24048417e-01 9.38300131e-01 9.84265645e-01]
  [7.94255896e-01 9.37280021e-01 5.02211265e-01]
  [1.43918283e-03 5.48839177e-01 8.06350547e-04]
  [8.63270329e-01 9.35170620e-01 3.10019083e-01]]

 [[2.10268219e-01 1.65810361e-01 3.76852340e-01]
  [2.01951040e-02 9.71584319e-01 6.68386743e-01]
  [4.35670714e-01 3.62105823e-01 9.94132010e-01]
  [6.40187398e-02 8.38471453e-01 6.51100502e-01]]]


#### Elegir un elemento aleatorio de un array

Dado un array, podemos elegir aleatoriamente un elemento suyo con el método `.choice()`

In [48]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x))

4


El método `.choice()` también consta del parámetro `size`, con lo cual podemos generar un array aleatorio con los elementos de un array dado:

In [49]:
print(random.choice(x, size = (3, 6)))

[[ 5 -2  5 -4 -5 -1]
 [ 1  4  5  2 -2 -1]
 [ 5 -5  2 -3 -4 -3]]


### Funciones universales

Las funciones universales son aquellas que operan sobre el objeto ndarray


Para crear una función universal propia, primero necesitamos definir una función. A continuación, hay que añadirla a `numpy` con el método `.frompyfunc()`, que tomará por parámetros la función `function`, el número de inputs (arrays), `inputs` y el número de arrays que devuelve, `outputs`:

In [3]:
def my_sum(x, y):
  return x + y

my_sum = np.frompyfunc(my_sum, 2, 1) 
# function = my_sum
# inputs = 2, pues my_sum toma dos arrays
# outputs = 1, pues my_sum devuelve un array, el array suma

a = np.array([1, 0, 7])
b = np.array([-1, 2, 5])
print(my_sum(a, b))

[0 2 12]


In [53]:
a = np.array([12, 0, 7])
b = np.array([8, 2, 5])

Aunque podemos crear nuestras propias funciones universales hay varias funcionaes universales definidas

El método `.add()` suma arrays elemento a elemento

In [54]:
print(np.add(a, b))

[20  2 12]


El método `.subtract()` resta arrays elemento a elemento


El método `.divide()` divide arrays elemento a elemento

El método `.power()` calcula la potencia del primer array elevado al segundo elemento a elemento 

El método `.divmod()` devuelve una tupla con 2 arrays, el primero contiene los cocientes y el segundo los restos de las divisiones enteras elemento a elemento 

El método `.absolute()` devuelve el valor absoluto de cada elemento de un array

El método `.sum()` nos calcula la suma de los elementos de un array

El método `.prod()` calcula el producto de los elementos de un array

El método `.log()` calcula el logaritmo neperiano de todos los elementos de un array.

...

In [55]:
test_arr = np.array([3, 2, 1, 7, 4])
print(f"Valor mínimo del array: {np.min(test_arr)}")
print(f"Posición del valor mínimo del array: {np.argmin(test_arr)}")
print(f"Posición del valor máximo del array: {np.argmax(test_arr)}")
print(f"Producto de los elementos del array: {np.prod(test_arr)}")
print(f"Media de los elementos del array: {np.mean(test_arr)}")
print(f"Mediana de los elementos del array: {np.median(test_arr)}")
print(f"Varianza de los elementos del array: {np.var(test_arr)}")
print(f"Desviación típica de los elementos del array: {np.std(test_arr)}")
print(f"Suma acumulativa de los elementos del array: {np.cumsum(test_arr)}")
print(f"Producto acumulativo de los elementos del array: {np.cumprod(test_arr)}")


Valor mínimo del array: 1
Posición del valor mínimo del array: 2
Posición del valor máximo del array: 3
Producto de los elementos del array: 168
Media de los elementos del array: 3.4
Mediana de los elementos del array: 3.0
Varianza de los elementos del array: 4.24
Desviación típica de los elementos del array: 2.0591260281974
Suma acumulativa de los elementos del array: [ 3  5  6 13 17]
Producto acumulativo de los elementos del array: [  3   6   6  42 168]


In [56]:
test_arr = np.array([3, 2, 1, 7, 4])
print(f"Suma 4 a los elementos del array: {test_arr + 4}")
print(f"Multiplica los elementos del array por 2: {test_arr * 2}")
print(f"Si quisiéramos repetir varias veces los elementos del array, haremos uso del método tile: {np.tile(test_arr, 2)}")
print(f"Si quisiéramos repetir cada elemento usaremos el método repeat: {np.repeat(test_arr, 2)}")
print(f"Podemos incluso indicar cuántas veces se repite cada elemento: {np.repeat(test_arr, [2,1,1,1,2])}")
print(f"Divide los elementos del array entre 2: {test_arr / 2}")
print(f"Elementos del array elevados al cubo: {test_arr**3}")
print(f"Exponenciación de los elementos del array: {np.exp(test_arr)}")
print(f"Logaritmo en base dos de los elementos del array: {np.log2(test_arr)}")


Suma 4 a los elementos del array: [ 7  6  5 11  8]
Multiplica los elementos del array por 2: [ 6  4  2 14  8]
Si quisiéramos repetir varias veces los elementos del array, haremos uso del método tile: [3 2 1 7 4 3 2 1 7 4]
Si quisiéramos repetir cada elemento usaremos el método repeat: [3 3 2 2 1 1 7 7 4 4]
Podemos incluso indicar cuántas veces se repite cada elemento: [3 3 2 1 7 4 4]
Divide los elementos del array entre 2: [1.5 1.  0.5 3.5 2. ]
Elementos del array elevados al cubo: [ 27   8   1 343  64]
Exponenciación de los elementos del array: [  20.08553692    7.3890561     2.71828183 1096.63315843   54.59815003]
Logaritmo en base dos de los elementos del array: [1.5849625  1.         0.         2.80735492 2.        ]



En `numpy` tenemos 5 métodos para redondear los decimales de un número

* `.trunc()` para truncar
* `.fix()` también para truncar
* `.around()` para redondear
* `.floor()` para redondear a la baja
* `.ceil()` para redondear a la alza

In [57]:
a = np.array([-5.1777, 5.7778, 5.5234])

In [58]:
print("Si truncamos con .trunc(), obtendremos {}".format(np.trunc(a)))
print("Si rendondeamos con .round() a 3 cifras decimales, obtendremos {}".format(np.round(a, 3)))

Si truncamos con .trunc(), obtendremos [-5.  5.  5.]
Si rendondeamos con .round() a 3 cifras decimales, obtendremos [-5.178  5.778  5.523]


In [59]:
test1_arr = np.array([1, 2, 3, 4])
test2_arr = np.array([4, 3, 2, 1])
print(f"Suma elemento a elemento de los dos arrays: {test1_arr + test2_arr}")
print(f"Si quisiéramos concatenarlos, como ocurre en Python, usaremos el método append: {np.append(test1_arr, test2_arr)}")
print(f"Podemos añadir un nuevo elemento al array mediante el método insert, al que indicaremos la posición: {np.insert(test1_arr, 0, 100)}")
print(f"Igualmente, haremos uso del método delete para eliminar elementos del array: {np.delete(test1_arr, 0)}")
print(f"Producto elemento a elemento de los dos arrays: {test1_arr * test2_arr}")
print(f"Diferencia elemento a elemento entre los dos arrays: {test1_arr - test2_arr}")
print(f"División elemento a elemento entre los dos arrays: {test1_arr / test2_arr}")
print(f"División entera elemento a elemento entre los dos arrays: {test1_arr // test2_arr}")


Suma elemento a elemento de los dos arrays: [5 5 5 5]
Si quisiéramos concatenarlos, como ocurre en Python, usaremos el método append: [1 2 3 4 4 3 2 1]
Podemos añadir un nuevo elemento al array mediante el método insert, al que indicaremos la posición: [100   1   2   3   4]
Igualmente, haremos uso del método delete para eliminar elementos del array: [2 3 4]
Producto elemento a elemento de los dos arrays: [4 6 6 4]
Diferencia elemento a elemento entre los dos arrays: [-3 -1  1  3]
División elemento a elemento entre los dos arrays: [0.25       0.66666667 1.5        4.        ]
División entera elemento a elemento entre los dos arrays: [0 0 1 4]


#### Matrices con `numpy`

Podemos crear matrices de numpy a partir de listas con el método `.matrix()`

In [60]:
M = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
print(M)
M.shape

[[ 1  0 -3  2]
 [ 2  0  1  1]
 [-1  0 -1  0]]


(3, 4)

Es sencillo sumar matrices, pues solamente necesitamos la función `+`

In [61]:
A = np.matrix([[1, 0, -3], [2, 0, 1], [-1, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3]])
matrixSum = A + B
matrixSum

matrix([[ 0, -2, -3],
        [ 0,  3,  1],
        [-1, -1, -3]])

También es sencillo hacer el producto matricial $A\cdot B$ con el método `.dot()`

In [62]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrixProd = A.dot(B)
matrixProd

matrix([[ 1,  0,  7],
        [-1, -3, -4],
        [ 1,  2,  3]])

Gracias a `numpy`, también es mucho más sencillo mostrar una matriz en forma de tabla, pues nos basta con hacer uso de la función `print()`:


In [63]:
print(matrixSum)
print(matrixProd)

[[ 0 -2 -3]
 [ 0  3  1]
 [-1 -1 -3]]
[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]


Para crear una matriz vacía, usamos el método `.empty()`, al que le indicamos por parámetro las dimensiones


In [64]:
A = np.empty((2, 3))  # 2 filas y 3 columnas
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


Para crear una matriz vacía con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.empty_like()`, al que le indicamos por parámetro la matriz existente

In [65]:
B = np.empty_like(A)  # Tendrá 2 filas y 3 columnas
print(B)

[[0. 0. 0.]
 [0. 0. 0.]]


Para crear una matriz nula, usamos el método `.zeros()`, al que le indicamos por parámetro las dimensiones

In [66]:
C = np.zeros((3, 5))  # Matriz nula de dimensiones 3 x 5
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Para crear una matriz de ceros con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.zeros_like()`, al que le indicamos por parámetro la matriz existente

In [67]:
# Tendrá 2 filas y 3 columnas y todos sus elementos valdrán 0
D = np.zeros_like(A)
print(D)

[[0. 0. 0.]
 [0. 0. 0.]]


Para crear una matriz de unos, usamos el método `.ones()`, al que le indicamos por parámetro las dimensiones


In [68]:
E = np.ones((1, 4))  # Matriz de unos de dimensiones 1 x 4
print(E)

[[1. 1. 1. 1.]]


Para crear una matriz de unos con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.ones_like()`, al que le indicamos por parámetro la matriz existente

In [69]:
# Tendrá 3 filas y 5 columnas y todos sus elementos valdrán 1
F = np.ones_like(C)
print(F)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
